insert into public.catalog_categories (slug, name, sort_order) values
  ('viennoiserie', 'Viennoiserie', 10),
  ('bread', 'Bread', 20),
  ('cake-pastry', 'Cakes and pastries', 30),
  ('savoury', 'Savoury food', 40),
  ('coffee', 'Coffee', 50),
  ('tea', 'Tea', 60),
  ('cold-drinks', 'Cold drinks', 70),
  ('dairy-alternatives', 'Dairy and alternatives', 80),
  ('ingredients', 'Ingredients', 90)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

with product_data (
  source_external_id,
  canonical_name,
  description,
  default_unit,
  category_slug,
  origin_country_codes,
  available_country_codes
) as (
  values
    ('croissant', 'Croissant', 'Classic laminated butter pastry.', 'item'::public.product_unit, 'viennoiserie', array['FR'], array['FR','BE','DE','ES','GB','IE','IT','NL','PT']),
    ('pain-au-chocolat', 'Pain au chocolat', 'Laminated pastry with dark chocolate batons.', 'item'::public.product_unit, 'viennoiserie', array['FR'], array['FR','BE','DE','ES','GB','IE','IT','NL','PT']),
    ('pain-aux-raisins', 'Pain aux raisins', 'Spiral pastry with custard and raisins.', 'item'::public.product_unit, 'viennoiserie', array['FR'], array['FR','BE','DE','GB','IE','NL']),
    ('chausson-aux-pommes', 'Chausson aux pommes', 'Puff pastry turnover filled with apple.', 'item'::public.product_unit, 'viennoiserie', array['FR'], array['FR','BE','GB','IE']),
    ('brioche', 'Brioche', 'Rich soft bread made with butter and eggs.', 'item'::public.product_unit, 'viennoiserie', array['FR'], array[]::text[]),
    ('cinnamon-bun', 'Cinnamon bun', 'Sweet rolled bun with cinnamon filling.', 'item'::public.product_unit, 'viennoiserie', array['SE'], array[]::text[]),
    ('cardamom-bun', 'Cardamom bun', 'Nordic sweet bun scented with cardamom.', 'item'::public.product_unit, 'viennoiserie', array['SE'], array['SE','NO','DK','FI','DE','NL','GB']),
    ('pastel-de-nata', 'Pastel de nata', 'Portuguese custard tart in crisp pastry.', 'item'::public.product_unit, 'cake-pastry', array['PT'], array[]::text[]),
    ('cornetto', 'Cornetto', 'Italian breakfast pastry, plain or filled.', 'item'::public.product_unit, 'viennoiserie', array['IT'], array['IT','FR','DE','ES','PT']),
    ('ensaimada', 'Ensaimada', 'Coiled sweet pastry from Mallorca.', 'item'::public.product_unit, 'viennoiserie', array['ES'], array['ES','PT','FR']),
    ('scone', 'Scone', 'British baked good served plain or with fruit.', 'item'::public.product_unit, 'cake-pastry', array['GB'], array['GB','IE','FR','NL','DE']),
    ('muffin', 'Muffin', 'Individual sweet quick bread.', 'item'::public.product_unit, 'cake-pastry', array['GB'], array[]::text[]),
    ('madeleine', 'Madeleine', 'Small shell-shaped French sponge cake.', 'item'::public.product_unit, 'cake-pastry', array['FR'], array[]::text[]),
    ('canele', 'Canele', 'Caramelised rum and vanilla pastry from Bordeaux.', 'item'::public.product_unit, 'cake-pastry', array['FR'], array['FR','BE','GB']),
    ('eclair', 'Eclair', 'Choux pastry filled with cream and glazed.', 'item'::public.product_unit, 'cake-pastry', array['FR'], array[]::text[]),
    ('tarte-tatin', 'Tarte Tatin', 'French upside-down caramelised apple tart.', 'portion'::public.product_unit, 'cake-pastry', array['FR'], array[]::text[]),
    ('lemon-drizzle-cake', 'Lemon drizzle cake', 'Moist lemon sponge with citrus syrup.', 'portion'::public.product_unit, 'cake-pastry', array['GB'], array['GB','IE','NL','DE']),
    ('carrot-cake', 'Carrot cake', 'Spiced carrot sponge with cream cheese icing.', 'portion'::public.product_unit, 'cake-pastry', array['GB'], array[]::text[]),
    ('basque-cheesecake', 'Basque cheesecake', 'Burnt-top creamy cheesecake from San Sebastian.', 'portion'::public.product_unit, 'cake-pastry', array['ES'], array[]::text[]),
    ('tiramisu', 'Tiramisu', 'Italian coffee and mascarpone dessert.', 'portion'::public.product_unit, 'cake-pastry', array['IT'], array[]::text[]),
    ('apple-strudel', 'Apple strudel', 'Layered pastry with spiced apple filling.', 'portion'::public.product_unit, 'cake-pastry', array['AT'], array['AT','DE','CZ','HU','NL']),
    ('black-forest-cake', 'Black Forest cake', 'Chocolate, cherry, and cream layer cake.', 'portion'::public.product_unit, 'cake-pastry', array['DE'], array['DE','AT','CH','NL']),
    ('baguette', 'Baguette', 'Long crusty French bread.', 'item'::public.product_unit, 'bread', array['FR'], array[]::text[]),
    ('sourdough-loaf', 'Sourdough loaf', 'Naturally leavened artisan bread.', 'item'::public.product_unit, 'bread', array[]::text[], array[]::text[]),
    ('ciabatta', 'Ciabatta', 'Open-crumb Italian white bread.', 'item'::public.product_unit, 'bread', array['IT'], array[]::text[]),
    ('focaccia', 'Focaccia', 'Olive-oil enriched Italian flatbread.', 'portion'::public.product_unit, 'bread', array['IT'], array[]::text[]),
    ('rye-bread', 'Rye bread', 'Dense bread made primarily with rye flour.', 'item'::public.product_unit, 'bread', array['DE'], array['DE','DK','SE','NO','FI','NL','PL']),
    ('soda-bread', 'Soda bread', 'Irish quick bread leavened with bicarbonate.', 'item'::public.product_unit, 'bread', array['IE'], array['IE','GB']),
    ('pretzel', 'Pretzel', 'Baked lye bread with a glossy crust.', 'item'::public.product_unit, 'bread', array['DE'], array['DE','AT','CH','NL']),
    ('bagel', 'Bagel', 'Boiled and baked ring-shaped bread.', 'item'::public.product_unit, 'bread', array['PL'], array[]::text[]),
    ('ham-cheese-croissant', 'Ham and cheese croissant', 'Croissant filled with ham and cheese.', 'item'::public.product_unit, 'savoury', array['FR'], array[]::text[]),
    ('quiche-lorraine', 'Quiche Lorraine', 'Savoury tart with egg, cream, and bacon.', 'portion'::public.product_unit, 'savoury', array['FR'], array[]::text[]),
    ('croque-monsieur', 'Croque monsieur', 'Grilled French ham and cheese sandwich.', 'item'::public.product_unit, 'savoury', array['FR'], array[]::text[]),
    ('panini', 'Panini', 'Pressed Italian-style filled sandwich.', 'item'::public.product_unit, 'savoury', array['IT'], array[]::text[]),
    ('empanada', 'Empanada', 'Filled baked or fried pastry turnover.', 'item'::public.product_unit, 'savoury', array['ES'], array['ES','PT','FR','IT']),
    ('tortilla-espanola', 'Tortilla espanola', 'Spanish potato and egg omelette.', 'portion'::public.product_unit, 'savoury', array['ES'], array['ES','PT','FR']),
    ('sausage-roll', 'Sausage roll', 'Seasoned sausage meat wrapped in puff pastry.', 'item'::public.product_unit, 'savoury', array['GB'], array['GB','IE']),
    ('espresso', 'Espresso', 'Single concentrated espresso coffee.', 'portion'::public.product_unit, 'coffee', array['IT'], array[]::text[]),
    ('double-espresso', 'Double espresso', 'Double shot of concentrated espresso.', 'portion'::public.product_unit, 'coffee', array['IT'], array[]::text[]),
    ('americano', 'Americano', 'Espresso lengthened with hot water.', 'portion'::public.product_unit, 'coffee', array['IT'], array[]::text[]),
    ('flat-white', 'Flat white', 'Espresso with thinly textured steamed milk.', 'portion'::public.product_unit, 'coffee', array[]::text[], array[]::text[]),
    ('cappuccino', 'Cappuccino', 'Espresso with steamed and foamed milk.', 'portion'::public.product_unit, 'coffee', array['IT'], array[]::text[]),
    ('cafe-latte', 'Cafe latte', 'Espresso with a larger proportion of steamed milk.', 'portion'::public.product_unit, 'coffee', array['IT'], array[]::text[]),
    ('cortado', 'Cortado', 'Espresso balanced with a small amount of warm milk.', 'portion'::public.product_unit, 'coffee', array['ES'], array[]::text[]),
    ('cafe-au-lait', 'Cafe au lait', 'Coffee served with hot milk.', 'portion'::public.product_unit, 'coffee', array['FR'], array[]::text[]),
    ('filter-coffee', 'Filter coffee', 'Batch-brewed or hand-filtered coffee.', 'portion'::public.product_unit, 'coffee', array[]::text[], array[]::text[]),
    ('black-tea', 'Black tea', 'Pot or cup of black tea.', 'portion'::public.product_unit, 'tea', array[]::text[], array[]::text[]),
    ('earl-grey', 'Earl Grey tea', 'Black tea scented with bergamot.', 'portion'::public.product_unit, 'tea', array['GB'], array[]::text[]),
    ('green-tea', 'Green tea', 'Pot or cup of green tea.', 'portion'::public.product_unit, 'tea', array[]::text[], array[]::text[]),
    ('fresh-orange-juice', 'Fresh orange juice', 'Freshly pressed orange juice.', 'portion'::public.product_unit, 'cold-drinks', array[]::text[], array[]::text[]),
    ('still-water', 'Still water', 'Bottled or filtered still water.', 'portion'::public.product_unit, 'cold-drinks', array[]::text[], array[]::text[]),
    ('sparkling-water', 'Sparkling water', 'Carbonated mineral or filtered water.', 'portion'::public.product_unit, 'cold-drinks', array[]::text[], array[]::text[]),
    ('whole-milk', 'Whole milk', 'Full-fat dairy milk.', 'l'::public.product_unit, 'dairy-alternatives', array[]::text[], array[]::text[]),
    ('semi-skimmed-milk', 'Semi-skimmed milk', 'Reduced-fat dairy milk.', 'l'::public.product_unit, 'dairy-alternatives', array[]::text[], array[]::text[]),
    ('oat-milk', 'Oat milk', 'Oat-based dairy alternative for drinks.', 'l'::public.product_unit, 'dairy-alternatives', array[]::text[], array[]::text[]),
    ('almond-milk', 'Almond milk', 'Almond-based dairy alternative for drinks.', 'l'::public.product_unit, 'dairy-alternatives', array[]::text[], array[]::text[]),
    ('soy-milk', 'Soy milk', 'Soy-based dairy alternative for drinks.', 'l'::public.product_unit, 'dairy-alternatives', array[]::text[], array[]::text[]),
    ('butter', 'Butter', 'Dairy butter for baking and service.', 'kg'::public.product_unit, 'ingredients', array[]::text[], array[]::text[]),
    ('wheat-flour', 'Wheat flour', 'Wheat flour used for bread and pastry.', 'kg'::public.product_unit, 'ingredients', array[]::text[], array[]::text[]),
    ('granulated-sugar', 'Granulated sugar', 'White granulated sugar.', 'kg'::public.product_unit, 'ingredients', array[]::text[], array[]::text[]),
    ('coffee-beans', 'Coffee beans', 'Roasted whole coffee beans.', 'kg'::public.product_unit, 'ingredients', array[]::text[], array[]::text[])
)
insert into public.catalog_products (
  source_name,
  source_external_id,
  canonical_name,
  description,
  default_unit,
  category_id,
  origin_country_codes,
  available_country_codes,
  is_verified
)
select
  'anteiku',
  data.source_external_id,
  data.canonical_name,
  data.description,
  data.default_unit,
  category.id,
  data.origin_country_codes,
  data.available_country_codes,
  true
from product_data data
join public.catalog_categories category on category.slug = data.category_slug
on conflict (source_name, source_external_id) do update set
  canonical_name = excluded.canonical_name,
  description = excluded.description,
  default_unit = excluded.default_unit,
  category_id = excluded.category_id,
  origin_country_codes = excluded.origin_country_codes,
  available_country_codes = excluded.available_country_codes,
  is_verified = excluded.is_verified,
  is_active = true;

with alias_data (product_slug, locale, alias) as (
  values
    ('croissant', 'en', 'butter croissant'),
    ('croissant', 'de', 'Buttercroissant'),
    ('pain-au-chocolat', 'en', 'chocolate croissant'),
    ('pain-au-chocolat', 'de', 'Schokocroissant'),
    ('pain-au-chocolat', 'es', 'napolitana de chocolate'),
    ('pain-aux-raisins', 'en', 'raisin swirl'),
    ('pastel-de-nata', 'en', 'Portuguese custard tart'),
    ('pastel-de-nata', 'pt', 'nata'),
    ('cornetto', 'en', 'Italian croissant'),
    ('cinnamon-bun', 'sv', 'kanelbulle'),
    ('cardamom-bun', 'sv', 'kardemummabulle'),
    ('scone', 'en', 'fruit scone'),
    ('canele', 'fr', 'canele de Bordeaux'),
    ('tarte-tatin', 'en', 'upside down apple tart'),
    ('basque-cheesecake', 'es', 'tarta de queso vasca'),
    ('apple-strudel', 'de', 'Apfelstrudel'),
    ('black-forest-cake', 'de', 'Schwarzwalder Kirschtorte'),
    ('baguette', 'fr', 'baguette tradition'),
    ('sourdough-loaf', 'fr', 'pain au levain'),
    ('sourdough-loaf', 'de', 'Sauerteigbrot'),
    ('rye-bread', 'de', 'Roggenbrot'),
    ('pretzel', 'de', 'Brezel'),
    ('quiche-lorraine', 'en', 'bacon quiche'),
    ('croque-monsieur', 'en', 'French ham cheese toastie'),
    ('tortilla-espanola', 'es', 'tortilla de patatas'),
    ('sausage-roll', 'de', 'Wurst im Blatterteig'),
    ('americano', 'fr', 'cafe allonge'),
    ('flat-white', 'fr', 'cafe blanc'),
    ('cafe-latte', 'en', 'latte'),
    ('cafe-latte', 'fr', 'cafe latte'),
    ('cortado', 'pt', 'pingo'),
    ('filter-coffee', 'fr', 'cafe filtre'),
    ('filter-coffee', 'de', 'Filterkaffee'),
    ('black-tea', 'fr', 'the noir'),
    ('black-tea', 'de', 'Schwarztee'),
    ('fresh-orange-juice', 'fr', 'jus orange frais'),
    ('fresh-orange-juice', 'es', 'zumo de naranja'),
    ('sparkling-water', 'fr', 'eau gazeuse'),
    ('sparkling-water', 'de', 'Sprudelwasser'),
    ('whole-milk', 'fr', 'lait entier'),
    ('whole-milk', 'de', 'Vollmilch'),
    ('semi-skimmed-milk', 'fr', 'lait demi-ecreme'),
    ('oat-milk', 'fr', 'lait avoine'),
    ('oat-milk', 'de', 'Hafermilch'),
    ('oat-milk', 'es', 'leche de avena'),
    ('almond-milk', 'fr', 'lait amande'),
    ('soy-milk', 'de', 'Sojamilch'),
    ('butter', 'fr', 'beurre'),
    ('butter', 'de', 'Butter'),
    ('wheat-flour', 'fr', 'farine de ble'),
    ('wheat-flour', 'de', 'Weizenmehl'),
    ('granulated-sugar', 'fr', 'sucre semoule'),
    ('coffee-beans', 'fr', 'cafe en grains'),
    ('coffee-beans', 'de', 'Kaffeebohnen')
)
insert into public.catalog_product_aliases (product_id, locale, alias, normalized_alias)
select product.id, data.locale, data.alias, ''
from alias_data data
join public.catalog_products product
  on product.source_name = 'anteiku'
 and product.source_external_id = data.product_slug
on conflict (product_id, locale, normalized_alias) do nothing;
